version: 2.1

executors:
  pytorch-bert-executor-36:
    working_directory: ~/pytorch-bert
    docker:
      - image: circleci/python:3.6

  pytorch-bert-executor-37:
    working_directory: ~/pytorch-bert
    docker:
      - image: circleci/python:3.7

commands:
  test-with-tox:
    steps:
      - checkout

      - run:
          name: install tox and codecov
          command: pip install --user tox codecov

      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "tox.ini" }}

      - restore_cache:
          key: google-pretrained-weight

      - run:
          name: test tox
          command: ~/.local/bin/tox

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - .tox

      - save_cache:
          key: google-pretrained-weight
          paths:
            - /tmp/bert-base
            - /tmp/bert-large

      - run:
          name: upload report to codecov
          command: ~/.local/bin/codecov

jobs:
  run-test-36:
    executor: pytorch-bert-executor-36
    environment:
      TOXENV: py36
    steps:
      - test-with-tox

  run-test-37:
    executor: pytorch-bert-executor-37
    environment:
      TOXENV: py37
    steps:
      - test-with-tox

workflows:
  version: 2
  pytorch-bert-workflow:
    jobs:
      - run-test-36
      - run-test-37
